[tool.poetry]
name = "trip-algorithm"
version = "0.1.0"
description = ""
authors = ["CSL426 <spark.cs.liao@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.10"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
